import Foundation

/// Constants shared by the app (client) and SwitchbackHelper (server). Compiled
/// into both targets: the Mach service name and the code-signing requirements
/// must match on both ends or the connection can't form.
enum HelperConstants {
    /// The helper's Mach service name (matches its launchd plist).
    static let machServiceName = "com.breed007.switchback.helper"

    /// The helper's bundle identifier, embedded in its binary's Info.plist.
    static let helperBundleID = "com.breed007.switchback.helper"

    /// The launchd plist inside `Contents/Library/LaunchDaemons`.
    static let plistName = "com.breed007.switchback.helper.plist"

    static let appBundleID = "com.breed007.switchback"

    /// Developer ID team that signs both ends.
    static let teamID = "YA83Q8FTH3"

    /// Requirement the helper enforces on every client: the Switchback app,
    /// signed by our team. The OS checks it per message, before helper code runs.
    static let clientRequirement =
        "identifier \"\(appBundleID)\" and anchor apple generic and " +
        "certificate leaf[subject.OU] = \"\(teamID)\""

    /// Requirement the app enforces on the helper. SMAppService already
    /// guarantees provenance; pinning costs nothing.
    static let helperRequirement =
        "identifier \"\(helperBundleID)\" and anchor apple generic and " +
        "certificate leaf[subject.OU] = \"\(teamID)\""

    /// XPC message keys.
    enum Key {
        static let op = "op"            // string (request)
        static let setID = "setID"      // string (request): the target SCNetworkSet ID
        static let ok = "ok"            // bool (reply)
        static let error = "error"      // string (reply, on failure)
    }

    /// Set IDs are generated by SystemConfiguration as UUID strings. Anything else
    /// (control characters, newlines, oversized input) is refused before the helper
    /// touches the preferences or writes the audit log, so input can't forge log lines.
    static func isWellFormedSetID(_ id: String) -> Bool {
        !id.isEmpty && id.utf8.count <= 64 && id.unicodeScalars.allSatisfy {
            ("A"..."Z").contains($0) || ("a"..."z").contains($0) || ("0"..."9").contains($0) || $0 == "-"
        }
    }

    /// The helper's only operation. It switches locations and nothing else.
    static let opSwitchTo = "switchTo"

    /// Reply error codes. The contract only grows; clients treat unknown codes as
    /// failures.
    enum ErrorCode {
        static let unknownOp = "unknown-op"
        static let unknownSet = "unknown-set"
        static let openPrefsFailed = "open-prefs-failed"
        static let commitFailed = "commit-failed"
        static let applyFailed = "apply-failed"
        /// `RequireAdminToSwitch` is on and the caller isn't an admin.
        static let policyDenied = "policy-denied"
    }
}
